name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.dotnet.os }}

    strategy:
      matrix:
        dotnet: [
          { os: 'windows-latest', version: '2', tfm: 'net20' },
          { os: 'windows-latest', version: '4', tfm: 'net40' },
          { os: 'ubuntu-latest',  version: '6', tfm: 'net6.0' },
          { os: 'ubuntu-latest',  version: '8', tfm: 'net8.0' },
      ]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      if: endsWith(matrix.dotnet.tfm, '.0') # only for .NET core
      # By default, tests will be executed under the latest installed version!
      uses: actions/setup-dotnet@v4
      id: stepid
      with:
        dotnet-version: ${{ matrix.dotnet.version }}
    - name: Create temporary global.json
      if: endsWith(matrix.dotnet.tfm, '.0') # only for .NET core
      run: echo '{"sdk":{"version":"${{steps.stepid.outputs.dotnet-version}}"}}' > ./global.json
    - name: Restore packages
      run: dotnet restore UrlBase64/UrlBase64.csproj -p:Configuration=Release -p:TargetFrameworks="${{ matrix.dotnet.tfm }}" -p:LangVersion="latest" --verbosity normal
    - name: Build solution
      run: dotnet build UrlBase64/UrlBase64.csproj -p:Configuration=Release -p:TargetFrameworks="${{ matrix.dotnet.tfm }}" -p:LangVersion="latest" --verbosity normal
    - name: Run tests
      # if: matrix.dotnet.tfm == 'net8.0' # only for .NET 8 because we are using collection literals
      if: endsWith(matrix.dotnet.tfm, '.0') # only for .NET core
      run: dotnet test -p:Configuration=Release --verbosity normal -p:TargetFrameworks="${{ matrix.dotnet.tfm }}" -p:LangVersion="latest"
